### ISSUE TITLE
Search pattern with include or exclude 

### ISSUE THREAD

**Issue by ishanuda** [ukushu/Ifrit#6]
Hi I am looking for a way to search for a pattern similar to the following:

"include this string" | "this string" ! "not this"

What is the search string I should pass in the search method.

Thank you.

**Comment by ukushu** [comment]
Currently, this behavior is not supported 

( and there are no plans to be implemented )

Fuse search needed to to search fuzzy results:

"od mn war" will find even "Old Man's War" and will display score of similarity.

But what you search for is standard `filter` function :)

```
someArrayOfStrings.filter { $0.contains("include this string") || $0.contains("this string") && !$0.contains("not this") }
```
