### ISSUE TITLE
Tag/release names are not usable by SPM

### ISSUE THREAD

**Issue by ladislas** [ukushu/Ifrit#7]
First a big thank you for this great package! :) 

It turns out your recent release/tag versions are not using the right formatting as you have a dot `.` after the `v`, such as in `v.2.0.3`

The correct name must be `v2.0.3`

the latest correct release/tag is `v1.0.1`

Could you please rename the most recent ones? 

Thanks a lot for your help :)

**Comment by ukushu** [comment]
will do a little bit later, thanks for attention

**Comment by ukushu** [comment]
<img width="200" alt="image" src="https://github.com/user-attachments/assets/c64608b3-b400-4e83-9f31-a83f7892cd4a">
